x-rhoaias-build: &rhoaias-build
  context: ../
  platforms:
    - linux/amd64
    - linux/arm64
  args:
    BUILD_VERSION: ${TAG_VERSION}

services:
  rhoaias-server:
    container_name: rhoaias-server
    image: chaldea/rhoaias-server
    restart: always
    build:
      dockerfile: ./docker/Dockerfile.server
      tags:
        - chaldea/rhoaias-server:latest
        - chaldea/rhoaias-server:${TAG_VERSION}
        - registry.cn-shanghai.aliyuncs.com/chaldea/rhoaias-server:latest
        - registry.cn-shanghai.aliyuncs.com/chaldea/rhoaias-server:${TAG_VERSION}
      <<: *rhoaias-build
    environment:
      RhoAias__Server__Bridge: 8024
      RhoAias__Server__Http: 80
      RhoAias__Server__Https: 443
    ports:
      - 8024:8024
    volumes:
      - rhoaias_server_data:/app/data
      - rhoaias_server_certs:/app/certs

  rhoaias-client:
    container_name: rhoaias-client
    image: chaldea/rhoaias-client
    restart: always
    build:
      dockerfile: ./docker/Dockerfile.client
      tags:
        - chaldea/rhoaias-client:latest
        - chaldea/rhoaias-client:${TAG_VERSION}
        - registry.cn-shanghai.aliyuncs.com/chaldea/rhoaias-client:latest
        - registry.cn-shanghai.aliyuncs.com/chaldea/rhoaias-client:${TAG_VERSION}
      <<: *rhoaias-build
    environment:
      RhoAias__Client__ServerUrl: http://rhoaias-server:8024
      RhoAias__Client__Token: NsRfN5VBOUi353fA6psQ
    depends_on:
      - rhoaias-server
  
  rhoaias-ingress:
    container_name: rhoaias-ingress
    image: chaldea/rhoaias-ingress
    restart: always
    build:
      dockerfile: ./docker/Dockerfile.ingress
      tags:
        - chaldea/rhoaias-ingress:latest
        - chaldea/rhoaias-ingress:${TAG_VERSION}
        - registry.cn-shanghai.aliyuncs.com/chaldea/rhoaias-ingress:latest
        - registry.cn-shanghai.aliyuncs.com/chaldea/rhoaias-ingress:${TAG_VERSION}
      <<: *rhoaias-build
    environment:
      RhoAias__Client__ServerUrl: http://rhoaias-server:8024
      RhoAias__Client__Token: rmpRZHT6nEe06lYglLqCHw
    volumes:
      - rhoaias_ingress_config:/root/.kube
    depends_on:
      - rhoaias-server
    
volumes: 
  rhoaias_server_data:
  rhoaias_server_certs:
  rhoaias_ingress_config: