---
# Source: ingress-rho-aias/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rho-aias-serviceaccount
  labels:
    helm.sh/chart: ingress-rho-aias-0.1.0
    app.kubernetes.io/name: ingress-rho-aias
    app.kubernetes.io/instance: ingress-rho-aias
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: ingress-rho-aias/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rho-aias-ingress-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - nodes
      - pods
      - secrets
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services/status
    verbs:
      - get
  - apiGroups:
      - networking.k8s.io
      - extensions
      - networking.internal.knative.dev
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - networking.k8s.io
      - extensions
      - networking.internal.knative.dev
    resources:
      - ingresses/status
    verbs:
      - get
      - update
---
# Source: ingress-rho-aias/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rho-aias-ingress-clusterrole-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rho-aias-ingress-clusterrole
subjects:
  - kind: ServiceAccount
    name: rho-aias-serviceaccount
---
# Source: ingress-rho-aias/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-rho-aias
  labels:
    helm.sh/chart: ingress-rho-aias-0.1.0
    app.kubernetes.io/name: ingress-rho-aias
    app.kubernetes.io/instance: ingress-rho-aias
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    app: ingress-rho-aias-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-rho-aias
      app.kubernetes.io/instance: ingress-rho-aias
      app: ingress-rho-aias-controller
  template:
    metadata:
      labels:
        helm.sh/chart: ingress-rho-aias-0.1.0
        app.kubernetes.io/name: ingress-rho-aias
        app.kubernetes.io/instance: ingress-rho-aias
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
        app: ingress-rho-aias-controller
    spec:
      serviceAccountName: rho-aias-serviceaccount
      containers:
        - name: ingress-rho-aias
          image: "chaldea/rhoaias-client:latest"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 500m
              memory: 500Mi
---
# Source: ingress-rho-aias/templates/ingressclass.yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: rho-aias
spec:
  controller: chaldea.cn/ingress-rho-aias
