kind: Namespace
apiVersion: v1
metadata:
  name: yarp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yarp-serviceaccount
  namespace: yarp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yarp-ingress-clusterrole
  namespace: yarp
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - nodes
      - pods
      - secrets
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services/status
    verbs:
      - get
  - apiGroups:
      - networking.k8s.io
      - extensions
      - networking.internal.knative.dev
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - networking.k8s.io
      - extensions
      - networking.internal.knative.dev
    resources:
      - ingresses/status
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yarp-ingress-clusterrole-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yarp-ingress-clusterrole
subjects:
  - kind: ServiceAccount
    name: yarp-serviceaccount
    namespace: yarp
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: yarp
spec:
  controller: microsoft.com/ingress-yarp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ingress-yarp-controller
  name: ingress-yarp
  namespace: yarp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-yarp-controller
  template:
    metadata:
      labels:
        app: ingress-yarp-controller
    spec:
      containers:
        - name: yarp-controller
          imagePullPolicy: IfNotPresent
          image: docker.flexem.com/test/rho-aias:1.0.0
          env:
            - name: RhoAias__IngressController__Enable
              value: "True"
            - name: RhoAias__Client__ServerUrl
              value: <SERVER_URL>
            - name: RhoAias__Client__Token
              value: <TOKEN>
      serviceAccountName: yarp-serviceaccount
