name: Build Docker Images

on:
  push:
    tags:
      - '*'

env:
  VERSION: 1.0.0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        run: |
          TAG=$(git describe --tags --abbrev=0 --match=v*[0-9.] || echo v${VERSION})
          if [ $? -eq 0 ]; then
            VERSION=${TAG:1}
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Docker Build
        working-directory: ./docker
        run: |
          echo "Build Version: ${VERSION}"
          docker compose build --build-arg BUILD_VERSION=${VERSION}
      - name: Docker Push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin ${{secrets.DOCKER_REPOSITORY}}
          docker push chaldea/rhoaias-server
          docker push chaldea/rhoaias-client
          docker push chaldea/rhoaias-ingress
          docker tag chaldea/rhoaias-server chaldea/rhoaias-server:${VERSION}
          docker tag chaldea/rhoaias-client chaldea/rhoaias-client:${VERSION}
          docker tag chaldea/rhoaias-ingress chaldea/rhoaias-ingress:${VERSION}
          docker push chaldea/rhoaias-server:${VERSION}
          docker push chaldea/rhoaias-client:${VERSION}
          docker push chaldea/rhoaias-ingress:${VERSION}