name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

env:
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Building ⚙
        run: |
          docker build -f docker/Dockerfile-Server -t chaldea/rhoaias-server:${VERSION} --build-arg="BUILD_VERSION=${VERSION}" .
          docker build -f docker/Dockerfile-Client -t chaldea/rhoaias-client:${VERSION} --build-arg="BUILD_VERSION=${VERSION}" .