name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

env:
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Building ⚙
        working-directory: ./docker
        run: |
          docker compose build --build-arg BUILD_VERSION=${VERSION}