name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "dashboard/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Building ⚙
        working-directory: ./docker
        run: |
          docker compose build