name: Release

on:
  push:
    branches:
      - release
    # tags:
    #   - '*'

env:
  VERSION: 0.1.1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        run: |
          TAG=$(git describe --tags --abbrev=0 --match=v*[0-9.] || echo v${VERSION})
          if [ $? -eq 0 ]; then
            VERSION=${TAG:1}
          fi
          echo "Build Version: ${VERSION}"
      - name: Docker Build
        run: |
          docker build -f docker/Dockerfile-Server -t chaldea/rhoaias-server:${VERSION} --build-arg="BUILD_VERSION=${VERSION}" .
          docker build -f docker/Dockerfile-Client -t chaldea/rhoaias-client:${VERSION} --build-arg="BUILD_VERSION=${VERSION}" .
      - name: Docker Push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin ${{secrets.DOCKER_REPOSITORY}}
          docker push chaldea/rhoaias-server:${VERSION}
          docker push chaldea/rhoaias-client:${VERSION}
          docker tag chaldea/rhoaias-server:${VERSION} chaldea/rhoaias-server:latest
          docker tag chaldea/rhoaias-client:${VERSION} chaldea/rhoaias-client:latest
          docker push chaldea/rhoaias-server:latest
          docker push chaldea/rhoaias-client:latest